### ISSUE TITLE
General question about supporting Java libraries

### ISSUE THREAD

**Issue by ooxi** [cincheo/j4ts#6]
Hi,

I'm not quite sure if I understand jsweet/j4ts correctly. If I have the Java source code of a library which does not depend on native methods or other libraries (besides the JRE which is supported by j4ts), I can simply use jsweet to transpile the hole library, correct?

And if I have a library using other libraries which are already transpiled, can jsweet transpile this library, too?

Is there an example project somewhere, demonstrating this usecase?

-- ooxi

**Comment by renaudpawlak** [comment]
> If I have the Java source code of a library which does not depend on native methods or other libraries (besides the JRE which is supported by j4ts), I can simply use jsweet to transpile the hole library, correct?

Correct. However in practice, there will probably still be some features missing when compiling a complex library. Also some adjustments to the code may be necessary because JSweet supports most (but not all) Java constructs.

> And if I have a library using other libraries which are already transpiled, can jsweet transpile this library, too?

Yes of course. The idea when you manage to compile a library is to create a candy out of it (a maven artifact) so that you can later use it as a dependency in your JSweet projects/libraries. See the JSweet documentation  (https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#packaging-a-jsweet-jar-candy).

> Is there an example project somewhere, demonstrating this usecase?

Unfortunately, there is not yet much examples about this. However, you can check how the J4TS candy is generated to extract the useful parts to generate a candy. There should be more examples/projects in the future but it is WIP.
